/**
 * Generates the highlighter sweep paths used by `src/components/Ground.tsx`.
 *
 * The look is a chisel-tip marker stroke: a broad band with ragged edges and
 * slightly bled ends. The obvious way to get that is an `feTurbulence` +
 * `feDisplacementMap` filter over a rect, which is what the design demo used —
 * but an SVG filter rasterises at render size, and a full-viewport one is
 * genuinely expensive on a low-end Android. So the displacement is done *here*,
 * once, and what ships is plain path data: resolution independent, no filter,
 * no runtime cost.
 *
 * Output is a TS module rather than SVG files on purpose. The doodles are
 * already inline SVG for the same reasons — no extra request, no CSP exception,
 * and the fill inherits from a token instead of being baked into an asset.
 *
 * Deterministic: the PRNG is seeded, so regenerating without changing SEED
 * produces byte-identical output and does not churn the diff.
 *
 *   node scripts/generate-sweeps.mjs
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const SEED = 20260823
const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../src/lib/sweeps.ts')

/** Mulberry32. Small, fast, and stable across Node versions. */
function prng(seed) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/**
 * Value noise over one dimension: a few octaves of interpolated random points.
 * Straight `random()` per sample gives a fuzzy edge, not a drawn one — the
 * edge of a real marker stroke wanders slowly and jitters slightly.
 */
function noise1d(rand, count, octaves) {
  const out = new Array(count).fill(0)
  let amp = 1
  let freq = 2
  let norm = 0
  for (let o = 0; o < octaves; o++) {
    // freq + 2, not freq + 1: at the final sample t === freq, so i0 === freq
    // and the lerp reads pts[i0 + 1]. One short produced NaN in the last
    // point of every edge, which silently collapsed the whole shape.
    const pts = Array.from({ length: freq + 2 }, () => rand() * 2 - 1)
    for (let i = 0; i < count; i++) {
      const t = (i / (count - 1)) * freq
      const i0 = Math.floor(t)
      const f = t - i0
      const s = f * f * (3 - 2 * f) // smoothstep
      out[i] += (pts[i0] * (1 - s) + pts[i0 + 1] * s) * amp
    }
    norm += amp
    amp *= 0.5
    freq *= 2
  }
  return out.map((v) => v / norm)
}

/** Catmull-Rom through the sampled points, emitted as cubic beziers. */
function smoothPath(points) {
  let d = `M${points[0][0].toFixed(0)} ${points[0][1].toFixed(0)}`
  for (let i = 0; i < points.length - 1; i++) {
    const p0 = points[i - 1] || points[i]
    const p1 = points[i]
    const p2 = points[i + 1]
    const p3 = points[i + 2] || p2
    const c1x = p1[0] + (p2[0] - p0[0]) / 6
    const c1y = p1[1] + (p2[1] - p0[1]) / 6
    const c2x = p2[0] - (p3[0] - p1[0]) / 6
    const c2y = p2[1] - (p3[1] - p1[1]) / 6
    d += `C${c1x.toFixed(0)} ${c1y.toFixed(0)} ${c2x.toFixed(0)} ${c2y.toFixed(0)} ${p2[0].toFixed(0)} ${p2[1].toFixed(0)}`
  }
  return d
}

/**
 * One stroke. `W`/`H` are the viewBox; the band sits inside with enough margin
 * that the ragged edge never clips.
 *
 * `taper` pulls the band's height in at both ends, which is what stops it
 * reading as a rectangle with a wobbly outline. A marker laid down and lifted
 * is thinner where the nib meets and leaves the paper.
 */
function sweep(rand, { W = 1000, H = 220, samples = 34, rag = 17, taper = 0.22 } = {}) {
  const midY = H / 2
  const halfH = H * 0.36
  const top = noise1d(rand, samples, 4)
  const bot = noise1d(rand, samples, 4)
  // Independent slow drift of the whole band, so it is not symmetric.
  const drift = noise1d(rand, samples, 2)

  const topPts = []
  const botPts = []
  for (let i = 0; i < samples; i++) {
    const t = i / (samples - 1)
    const x = t * W
    // Ends taper: 1 at the middle, `1 - taper` at either end.
    const ends = 1 - taper * Math.pow(Math.abs(t * 2 - 1), 2.2)
    const dy = drift[i] * H * 0.035
    topPts.push([x, midY - halfH * ends + top[i] * rag + dy])
    botPts.push([x, midY + halfH * ends + bot[i] * rag + dy])
  }

  // Top edge left to right, straight across the right end, bottom edge back.
  // Built as one point list so the outline closes cleanly and the string is
  // produced in a single pass.
  return smoothPath([...topPts, ...botPts.reverse()]) + 'Z'
}

const rand = prng(SEED)
const variants = Array.from({ length: 4 }, (_, i) =>
  sweep(rand, { rag: 14 + i * 4, taper: 0.14 + i * 0.06 }),
)

const banner = `/**
 * GENERATED by scripts/generate-sweeps.mjs. Do not edit by hand.
 *
 * Highlighter sweep outlines, pre-displaced so nothing filters at runtime.
 * Each path is drawn in a 1000x220 viewBox and stretched to its section with
 * preserveAspectRatio="none"; the edge noise is low frequency enough that the
 * distortion reads as a wider or narrower marker rather than as a stretch.
 */

export const SWEEP_VIEWBOX = '0 0 1000 220'

/** Five strokes so repeated sections never show the identical edge. */
export const SWEEPS: readonly string[] = [
`

writeFileSync(
  OUT,
  banner + variants.map((d) => `  '${d}',`).join('\n') + '\n]\n',
  'utf8',
)
console.log(`wrote ${OUT} (${variants.length} sweeps)`)
